class Application:


    def __init__(self, SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE, CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, CNT_CHILDREN = None, AMT_INCOME_TOTAL = None, AMT_CREDIT = None , AMT_ANNUITY = None, AMT_GOODS_PRICE = None, NAME_TYPE_SUITE = None, NAME_INCOME_TYPE = None, NAME_EDUCATION_TYPE = None, NAME_FAMILY_STATUS = None, NAME_HOUSING_TYPE = None, REGION_POPULATION_RELATIVE = None):
        self.SK_ID_CURR = SK_ID_CURR
        self.TARGET = TARGET
        self.NAME_CONTRACT_TYPE = NAME_CONTRACT_TYPE
        self.CODE_GENDER = CODE_GENDER
        self.FLAG_OWN_CAR = FLAG_OWN_CAR
        self.FLAG_OWN_REALTY = FLAG_OWN_REALTY
        self.CNT_CHILDREN = CNT_CHILDREN
        self.AMT_INCOME_TOTAL = AMT_INCOME_TOTAL
        self.AMT_CREDIT = AMT_CREDIT
        self.AMT_ANNUITY = AMT_ANNUITY
        self.AMT_GOODS_PRICE = AMT_GOODS_PRICE
        self.NAME_TYPE_SUITE = NAME_TYPE_SUITE
        self.NAME_INCOME_TYPE = NAME_INCOME_TYPE
        self.NAME_EDUCATION_TYPE = NAME_EDUCATION_TYPE
        self.NAME_FAMILY_STATUS = NAME_FAMILY_STATUS
        self.NAME_HOUSING_TYPE = NAME_HOUSING_TYPE
        self.REGION_POPULATION_RELATIVE = REGION_POPULATION_RELATIVE