class Application:


    def __init__(self, SK_ID_CURR = None, TARGET = None, NAME_CONTRACT_TYPE = None, CODE_GENDER = None, FLAG_OWN_CAR = None, FLAG_OWN_REALTY = None, CNT_CHILDREN = None, AMT_INCOME_TOTAL = None, AMT_CREDIT = None , AMT_ANNUITY = None, AMT_GOODS_PRICE = None, NAME_TYPE_SUITE = None, NAME_INCOME_TYPE = None, NAME_EDUCATION_TYPE = None, NAME_FAMILY_STATUS = None, NAME_HOUSING_TYPE = None, REGION_POPULATION_RELATIVE = None, DAYS_ID_PUBLISH = None, OCCUPATION_TYPE = None, WEEKDAY_APPR_PROCESS_START = None, ORGANIZATION_TYPE = None, YEARS_BEGINEXPLUATATION_AVG = None, ELEVATORS_AVG = None, LANDAREA_AVG = None, LIVINGAREA_AVG = None, NONLIVINGAREA_AVG = None, APARTMENTS_MODE = None, BASEMENTAREA_MODE = None, FLOORSMAX_MODE = None, LIVINGAPARTMENTS_AVG = None, EXT_SOURCE_1 = None, EXT_SOURCE_2 = None, EXT_SOURCE_3 = None, FONDKAPREMONT_MODE = None, HOUSETYPE_MODE = None, WALLSMATERIAL_MODE = None, FLAG_DOCUMENT_5 = None, FLAG_DOCUMENT_17 = None):


        
        self.SK_ID_CURR = SK_ID_CURR
        self.TARGET = TARGET #Presente
        self.NAME_CONTRACT_TYPE = NAME_CONTRACT_TYPE #Presente
        self.CODE_GENDER = CODE_GENDER #Presente
        self.FLAG_OWN_CAR = FLAG_OWN_CAR #Presente
        self.FLAG_OWN_REALTY = FLAG_OWN_REALTY #Presente
        self.CNT_CHILDREN = CNT_CHILDREN
        self.AMT_INCOME_TOTAL = AMT_INCOME_TOTAL
        self.AMT_CREDIT = AMT_CREDIT
        self.AMT_ANNUITY = AMT_ANNUITY
        self.AMT_GOODS_PRICE = AMT_GOODS_PRICE
        self.NAME_TYPE_SUITE = NAME_TYPE_SUITE #Presente
        self.NAME_INCOME_TYPE = NAME_INCOME_TYPE
        self.NAME_EDUCATION_TYPE = NAME_EDUCATION_TYPE
        self.NAME_FAMILY_STATUS = NAME_FAMILY_STATUS #Presente
        self.NAME_HOUSING_TYPE = NAME_HOUSING_TYPE
        self.REGION_POPULATION_RELATIVE = REGION_POPULATION_RELATIVE #Presente
        """
        self.DAYS_BIRTH = DAYS_BIRTH
        self.DAYS_EMPLOYED = DAYS_EMPLOYED
        self.DAYS_REGISTRATION = DAYS_REGISTRATION
        """
        self.DAYS_ID_PUBLISH = DAYS_ID_PUBLISH #Presente
        """
        self.OWN_CAR_AGE = OWN_CAR_AGE
        self.FLAG_MOBIL = FLAG_MOBIL
        self.FLAG_EMP_PHONE = FLAG_EMP_PHONE
        self.FLAG_WORK_PHONE = FLAG_WORK_PHONE
        self.FLAG_CONT_MOBILE = FLAG_CONT_MOBILE
        self.FLAG_PHONE = FLAG_PHONE
        self.FLAG_EMAIL = FLAG_EMAIL
        """
        self.OCCUPATION_TYPE = OCCUPATION_TYPE #Presente
        """
        self.CNT_FAM_MEMBERS = CNT_FAM_MEMBERS
        self.REGION_RATING_CLIENT = REGION_RATING_CLIENT
        self.REGION_RATING_CLIENT_W_CITY = REGION_RATING_CLIENT_W_CITY
        """
        self.WEEKDAY_APPR_PROCESS_START = WEEKDAY_APPR_PROCESS_START #Presente
        """
        self.HOUR_APPR_PROCESS_START = HOUR_APPR_PROCESS_START
        self.REG_REGION_NOT_LIVE_REGION = REG_REGION_NOT_LIVE_REGION
        self.REG_REGION_NOT_WORK_REGION = REG_REGION_NOT_WORK_REGION
        self.LIVE_REGION_NOT_WORK_REGION = LIVE_REGION_NOT_WORK_REGION
        self.REG_CITY_NOT_LIVE_CITY = REG_CITY_NOT_LIVE_CITY
        self.REG_CITY_NOT_WORK_CITY = REG_CITY_NOT_WORK_CITY
        self.LIVE_CITY_NOT_WORK_CITY = LIVE_CITY_NOT_WORK_CITY
        """
        self.ORGANIZATION_TYPE = ORGANIZATION_TYPE #Presente
        self.EXT_SOURCE_1 = EXT_SOURCE_1 #Presente
        self.EXT_SOURCE_2 = EXT_SOURCE_2 #Presente
        self.EXT_SOURCE_3 = EXT_SOURCE_3 #Presente
        """
        self.APARTMENTS_AVG = APARTMENTS_AVG
        self.BASEMENTAREA_AVG = BASEMENTAREA_AVG
        """
        self.YEARS_BEGINEXPLUATATION_AVG = YEARS_BEGINEXPLUATATION_AVG #Presente
        """ 
        self.YEARS_BUILD_AVG = YEARS_BUILD_AVG
        self.COMMONAREA_AVG = COMMONAREA_AVG
        """
        self.ELEVATORS_AVG = ELEVATORS_AVG #Presente
        """
        self.ENTRANCES_AVG = ENTRANCES_AVG
        self.FLOORSMAX_AVG = FLOORSMAX_AVG
        self.FLOORSMIN_AVG = FLOORSMIN_AVG
        """
        self.LANDAREA_AVG = LANDAREA_AVG #Presente
        self.LIVINGAPARTMENTS_AVG = LIVINGAPARTMENTS_AVG #Presente
        self.LIVINGAREA_AVG = LIVINGAREA_AVG #Presente
        """
        self.NONLIVINGAPARTMENTS_AVG = NONLIVINGAPARTMENTS_AVG
        """
        self.NONLIVINGAREA_AVG = NONLIVINGAREA_AVG #Presente
        self.APARTMENTS_MODE = APARTMENTS_MODE #Presente
        self.BASEMENTAREA_MODE = BASEMENTAREA_MODE #Presente
        """
        self.YEARS_BEGINEXPLUATATION_MODE = YEARS_BEGINEXPLUATATION_MODE
        self.YEARS_BUILD_MODE = YEARS_BUILD_MODE
        self.COMMONAREA_MODE = COMMONAREA_MODE
        self.ELEVATORS_MODE = ELEVATORS_MODE
        self.ENTRANCES_MODE = ENTRANCES_MODE
        """
        self.FLOORSMAX_MODE = FLOORSMAX_MODE #Presente
        """
        self.FLOORSMIN_MODE = FLOORSMIN_MODE
        self.LANDAREA_MODE = LANDAREA_MODE
        self.LIVINGAPARTMENTS_MODE = LIVINGAPARTMENTS_MODE 
        self.LIVINGAREA_MODE = LIVINGAREA_MODE
        self.NONLIVINGAPARTMENTS_MODE = NONLIVINGAPARTMENTS_MODE
        self.NONLIVINGAREA_MODE = NONLIVINGAREA_MODE
        self.APARTMENTS_MEDI = APARTMENTS_MEDI
        self.BASEMENTAREA_MEDI = BASEMENTAREA_MEDI
        self.YEARS_BEGINEXPLUATATION_MEDI = YEARS_BEGINEXPLUATATION_MEDI
        self.YEARS_BUILD_MEDI = YEARS_BUILD_MEDI
        self.COMMONAREA_MEDI = COMMONAREA_MEDI
        self.ELEVATORS_MEDI = ELEVATORS_MEDI
        self.ENTRANCES_MEDI = ENTRANCES_MEDI
        self.FLOORSMAX_MEDI = FLOORSMAX_MEDI
        self.FLOORSMIN_MEDI = FLOORSMIN_MEDI
        self.LANDAREA_MEDI = LANDAREA_MEDI
        self.LIVINGAPARTMENTS_MEDI = LIVINGAPARTMENTS_MEDI
        self.LIVINGAREA_MEDI = LIVINGAREA_MEDI
        self.NONLIVINGAPARTMENTS_MEDI = NONLIVINGAPARTMENTS_MEDI
        self.NONLIVINGAREA_MEDI = NONLIVINGAREA_MEDI
        """
        self.FONDKAPREMONT_MODE = FONDKAPREMONT_MODE #Présente
        self.HOUSETYPE_MODE = HOUSETYPE_MODE #Présente
        """
        self.TOTALAREA_MODE = TOTALAREA_MODE
        """
        self.WALLSMATERIAL_MODE = WALLSMATERIAL_MODE #Présente
        """
        self.EMERGENCYSTATE_MODE = EMERGENCYSTATE_MODE
        self.OBS_30_CNT_SOCIAL_CIRCLE = OBS_30_CNT_SOCIAL_CIRCLE
        self.DEF_30_CNT_SOCIAL_CIRCLE = DEF_30_CNT_SOCIAL_CIRCLE
        self.OBS_60_CNT_SOCIAL_CIRCLE = OBS_60_CNT_SOCIAL_CIRCLE
        self.DEF_60_CNT_SOCIAL_CIRCLE = DEF_60_CNT_SOCIAL_CIRCLE
        self.DAYS_LAST_PHONE_CHANGE = DAYS_LAST_PHONE_CHANGE
        self.FLAG_DOCUMENT_2 = FLAG_DOCUMENT_2
        self.FLAG_DOCUMENT_3 = FLAG_DOCUMENT_3
        self.FLAG_DOCUMENT_4 = FLAG_DOCUMENT_4
        """
        self.FLAG_DOCUMENT_5 = FLAG_DOCUMENT_5 #Présente
        """
        self.FLAG_DOCUMENT_6 = FLAG_DOCUMENT_6
        self.FLAG_DOCUMENT_7 = FLAG_DOCUMENT_7
        self.FLAG_DOCUMENT_8 = FLAG_DOCUMENT_8
        self.FLAG_DOCUMENT_9 = FLAG_DOCUMENT_9
        self.FLAG_DOCUMENT_10 = FLAG_DOCUMENT_10
        self.FLAG_DOCUMENT_11 = FLAG_DOCUMENT_11
        self.FLAG_DOCUMENT_12 = FLAG_DOCUMENT_12
        self.FLAG_DOCUMENT_13 = FLAG_DOCUMENT_13
        self.FLAG_DOCUMENT_14 = FLAG_DOCUMENT_14
        self.FLAG_DOCUMENT_15 = FLAG_DOCUMENT_15
        self.FLAG_DOCUMENT_16 = FLAG_DOCUMENT_16
        """
        self.FLAG_DOCUMENT_17 = FLAG_DOCUMENT_17 #Présente
        """
        self.FLAG_DOCUMENT_18 = FLAG_DOCUMENT_18
        self.FLAG_DOCUMENT_19 = FLAG_DOCUMENT_19
        self.FLAG_DOCUMENT_20 = FLAG_DOCUMENT_20
        self.FLAG_DOCUMENT_21 = FLAG_DOCUMENT_21
        self.AMT_REQ_CREDIT_BUREAU_HOUR = AMT_REQ_CREDIT_BUREAU_HOUR
        self.AMT_REQ_CREDIT_BUREAU_DAY = AMT_REQ_CREDIT_BUREAU_DAY
        self.AMT_REQ_CREDIT_BUREAU_WEEK = AMT_REQ_CREDIT_BUREAU_WEEK
        self.AMT_REQ_CREDIT_BUREAU_MON = AMT_REQ_CREDIT_BUREAU_MON
        self.AMT_REQ_CREDIT_BUREAU_QRT = AMT_REQ_CREDIT_BUREAU_QRT
        self.AMT_REQ_CREDIT_BUREAU_YEAR = AMT_REQ_CREDIT_BUREAU_YEAR
        """